// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcjjuqjobmmffonblhft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjamp1cWpvYm1tZmZvbmJsaGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTk4MTQsImV4cCI6MjA2OTA5NTgxNH0.mjfNVrrOMekwYdtqVbdJ4SvZmzedhWkpLFQ-OC-qpQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});